### ISSUE TITLE
12-06-2015 Adjustment 

### ISSUE THREAD

**Issue by vincent1332** [project-spot/spot-web-preview#1]
![news](https://cloud.githubusercontent.com/assets/8881774/8130864/bce57e08-1148-11e5-9912-bf8fd956dba5.png)
1. News Presentation
   1. Push button on upper top side [(icon) Push] - font color RGB 255, 127, 0 
   2. user name below title [(icon) username]
   3. image on top of the text, adjusted by ratio
   4. text below image, more button should still be provided
   5. date of post (timestamp) on the bottom left corner
   6. number of push and number of comment on the bottom right  [(icon) push count, (icon) comment count]
2. Recommended event presentation
   1. Push button on top right corner same as news
   2. image below "Recommended Event", resize by ratio
   3. Details on the right 
      Event Title 
      [(icon) time of event]
      [(icon) region of event]
   4. push and comment count on the bottom right corner, same as news
3. Advertisement Presentation (right hand side)
   Overall structure
       Title
       Company name
       description (max. 5 lines or less, depends )
       image 
       separation line
   repeat
   Total 3 advertisements

**Comment by hkgsherlock** [comment]
as you wish

**Comment by hkgsherlock** [comment]
those icons are being put into new repo in the org, and be set as sub-mod of this repo
if there are any changes to the icons, commit and them [there](https://github.com/project-spot/icons-storage).
